### ISSUE TITLE
ToDo v3

### ISSUE THREAD

**Issue by baking-code** [baking-code/portfolio#1]
- [x] Establish routing: About me, hobbies, experience, gallery
- [x] Create content blocks with title
- [ ] Create timeline with scroll for experience page
- [ ] Add content for hobbies page
- [ ] Define colour palette
- [ ] Sort out print/PDF view
